backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads/images"   # Where images are stored
public_folder: "/uploads/images"        # How they're referenced in the site

collections:
  - name: "images"
    label: "Images"
    extension: "json"
    format: "json"
    files:
      - file: "files.json"   # Always write at repo root
        label: "Image List"
        name: "images"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "file", widget: "image" }
              - { label: "Category", name: "category", widget: "select", options: ["Featured", "Weddings", "Graduations", "Birthdays", "Random"] }
              - { label: "Date", name: "date", widget: "datetime" }
