backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads/images"   # where uploaded images are stored
public_folder: "/uploads/images"        # public URL path to images

collections:
  - name: "images"
    label: "Images"
    folder: "public/uploads/images"     # store entries in this folder
    create: true
    delete: true
    extension: "json"
    format: "json"
    identifier_field: "title"

    # use the files.json index
    files:
      - file: "public/uploads/images/files.json"
        label: "Image List"
        name: "image_list"
        fields:
          - { name: "images", label: "Images", widget: "list", fields: [
              { name: "title", label: "Title", widget: "string" },
              { name: "file", label: "File", widget: "image" },
              { name: "category", label: "Category", widget: "string" },
              { name: "date", label: "Date", widget: "datetime" }
            ]
          }
