backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads/images"   # where uploaded images are stored
public_folder: "/uploads/images"        # public URL path to images

collections:
  - name: "images"
    label: "Images"
    folder: "public"     # store entries in this folder
    create: true
    delete: true
    extension: "json"
    format: "json"
    identifier_field: "title"
    fields:
          - { name: "images", label: "Images", widget: "list", fields: [
              { name: "title", label: "Title", widget: "string" },
              { name: "file", label: "File", widget: "image" },
              { name: "category", label: "Category", widget: "select", options: ["Featured", "Weddings", "Graduations"] },
              { name: "date", label: "Date", widget: "datetime" }
            ]
          }

  - name: "Client-Images"
    label: "Client-Images"
    folder: "public"
    create: true
    delete: true
    extension: "json"
    format: "json"
    identifier_field: "title"
    slug: {{client-images}}
    fields: 
          - {
              name: "client-images", label: "Client-Images", widget: "list", fields: [
              {name: "title", label: "Title", widget: "string"},
              {name : "testimonial", label: "Testimonial", widget: "string"}, 
              {name: "file", label: "File", widget: "image"},
              {name: "user-image", label: "User-Image", widget: "image"}
             ]
             
          }

          