backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads/images"
public_folder: "/uploads/images"

collections:
  - name: "images"
    label: "Images"
    folder: "public/uploads/images"
    create: true
    extension: "jpg"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "file", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["Featured", "Weddings", "Graduations", "Birthdays", "Random"]}
      - { label: "Date", name: "date", widget: "datetime" }
