backend:
  name: git-gateway
  branch: main

media_folder: "photo-studio-with-vite/public/uploads/images"
public_folder: "/uploads/images"

collections:
  - name: "images"
    label: "Images"
    extension: "json"
    format: "json"
    files:
      - file: "./photo-studio-with-vite/files.json"   # <-- corrected path
        label: "Image List"
        name: "images"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "file", widget: "image" }
              - { label: "Category", name: "category", widget: "string", required: false }
              - { label: "Date", name: "date", widget: "datetime" }

