name: Update Image Files JSON

on:
  push:
    paths:
      - "public/uploads/images/**/*.{jpg,jpeg,png,gif}"

jobs:
  update-files-json:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Generate files.json in public
        run: |
          cd public/uploads/images || exit
          echo '{"images": [' > ../../files.json
          first=true

          find . -type f \( \
            -iname "*.jpg" -o \
            -iname "*.jpeg" -o \
            -iname "*.png" -o \
            -iname "*.gif" \
          \) | while read -r filepath; do

            # Remove leading './'
            clean_path="${filepath#./}"

            # Add comma if not the first entry
            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> ../../files.json
            fi

            # Write JSON object with placeholders
            echo "  {\"title\": \"\", \"file\": \"./uploads/images/${clean_path}\", \"category\": \"\", \"date\": \"\"}" >> ../../files.json
          done

          echo "]}" >> ../../files.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/files.json
          git commit -m "Auto-update public/files.json" || echo "No changes to commit"
          git push origin main
