name: Sync CMS files.json

on:
  push:
    branches:
      - main

jobs:
  copy-files-json:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Copy CMS files.json into public
        run: |
          mkdir -p public
          cp files.json public/files.json
          echo "Copied CMS files.json into public/"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/files.json
          git commit -m "Sync files.json into public/" || echo "No changes to commit"
          git push origin main
