name: Update Image Files JSON
on:
  push:
    paths:
      - "public/uploads/images/**/*.{jpg,jpeg,png,gif}"

jobs:
  update-files-json:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Install jq
        run: sudo apt-get install jq -y
      
      - name: Generate files.json in public folder
        run: |
          JSON_FILE="public/files.json"
          IMAGE_DIR="public/uploads/images"
          
          # Create public directory if it doesn't exist
          mkdir -p public
          
          # Check if JSON file exists and read existing data
          if [ -f "$JSON_FILE" ]; then
            EXISTING_JSON=$(cat "$JSON_FILE")
          else
            EXISTING_JSON='{"images":[]}'
          fi
          
          # Generate new JSON with current images
          NEW_JSON=$(jq -n '{images: []}')
          
          # Find all image files and add to JSON
          while IFS= read -r -d '' file; do
            # Get filename only
            FILENAME=$(basename "$file")
            # Add to JSON with relative path from public folder
            NEW_JSON=$(echo "$NEW_JSON" | jq --arg f "$FILENAME" '.images += [{"title":"", "file":"./uploads/images/"+$f, "category":"", "date":""}]')
          done < <(find "$IMAGE_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) -print0)
          
          # Merge existing and new images, keeping unique entries by file path
          MERGED=$(jq -s '{images: (.[0].images + .[1].images | unique_by(.file))}' <(echo "$EXISTING_JSON") <(echo "$NEW_JSON"))
          
          # Write the merged JSON to public/files.json
          echo "$MERGED" > "$JSON_FILE"
          
          echo "Generated files.json with $(echo "$MERGED" | jq '.images | length') images"
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/files.json
          git commit -m "Auto-update public/files.json" || echo "No changes to commit"
          git push origin main