name: Generate Image Index

on:
  push:
    branches:
      - main


jobs:
  generate-images-json:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Generate files.json in public/uploads/images
        run: |
          cd public/uploads/images || exit
          echo '{"images": [' > files.json
          first=true

          find . -type f \( \
            -iname "*.jpg" -o \
            -iname "*.jpeg" -o \
            -iname "*.png" -o \
            -iname "*.gif" \
          \) | while read -r filepath; do
            clean_path="${filepath#./}"

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> files.json
            fi

            echo "  {\"title\": \"\", \"file\": \"./uploads/images/${clean_path}\", \"category\": \"\", \"date\": \"\"}" >> files.json
          done

          echo "]}" >> files.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/uploads/images/files.json
          git commit -m "Auto-update image index" || echo "No changes to commit"
          git push origin main
