name: Update Image Files

on:
  push:
    branches:
      - main

jobs:
  update-files-json:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Generate files.json in public
        run: |
          JSON_FILE="public/files.json"
          IMAGE_DIR="public/uploads/images"

          echo '{"images": [' > "$JSON_FILE"
          first=true

          find "$IMAGE_DIR" -type f \( \
            -iname "*.jpg" -o \
            -iname "*.jpeg" -o \
            -iname "*.png" -o \
            -iname "*.gif" \
          \) | while read -r filepath; do

            # Make the path relative to public/
            clean_path="${filepath#public/}"

            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> "$JSON_FILE"
            fi

            echo "  {\"title\": \"\", \"file\": \"./${clean_path}\", \"category\": \"\", \"date\": \"\"}" >> "$JSON_FILE"
          done

          echo "]}" >> "$JSON_FILE"

          echo "Generated $(wc -l < "$JSON_FILE") lines in $JSON_FILE"
          ls -l public/

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/files.json
          git commit -m "Auto-update public/files.json" || echo "No changes to commit"
          git push origin main
